name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Remplacer 3.1 par 3.9 ou 3.10

      # Étape 3: Installation des dépendances
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Étape 4: Exécution des tests
      - name: Run tests
        run: |
          pytest

      # Étape 5: Connexion à Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 6: Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ton-compte/ton-image:latest .

      # Étape 7: Pousser l'image Docker sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ton-compte/ton-image:latest

