name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Installer les dépendances Python
        run: pip install -r requirements.txt

      - name: Construire l’image Docker
        run: docker build -t ton-utilisateur-docker/ton-image:latest .

      - name: Se connecter à Docker Hub et push l’image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ton-utilisateur-docker/ton-image:latest
